[package]
name = "updater"
description = "NoxLauncher Updater for NoxLauncher"
version = "0.6.1"
edition = "2021"

[dependencies]
zip = "2.2.1"

[profile.release]
opt-level = 'z'
codegen-units = 1
lto = true
panic = "abort"
debug = false
strip = true
incremental = true
