[package]
name = "noxlauncher-updater"
description = "NoxLauncher Updater for NoxLauncher"
version = "0.6.0"
edition = "2021"

[dependencies]
zip = "2.2.1"
regex = "1.11.1"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"
debug = false
strip = true
incremental = true
